version: '3.12'

services:
  backend:
    build: .
    ports:
      - "3569:5000"
    restart: unless-stopped
    # Optional healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/predict"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
