version: '3.12'

environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=7
deploy:
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: 1
          capabilities: [gpu]
services:
  backend:
    build: ./image_classifier_api
    ports:
      - "3215:5000"
    restart: unless-stopped
    # Optional healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://194.171.191.226:3215/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
